hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/order-backend
  tag: production-981f97b
networkPolicy:
  allowedServices:
    - identity-backend
    - catalog-backend
    - payment-backend
    - user-backend
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1102Mi
  requests:
    cpu: 17m
    memory: 716Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: production
